### ISSUE TITLE
[BUG]: Error in LLM Blocks 

### ISSUE THREAD

**Issue by iam-vipin** [llmshare/llmproto#22]
Right now we have this error with `CohereAI` and `GooglePalmAI` *LLM* Blocks 

![image](https://github.com/llmshare/llmproto/assets/99081689/b8724b44-3b70-41ce-a9d5-c5b35c6c5ffb)

[Screencast from 2023-10-25 23-10-26.webm](https://github.com/llmshare/llmproto/assets/99081689/bd3974f4-bb3a-4c3b-8fb9-ad9c9d3eb2ea)

**Comment by Sing-Li** [comment]
@David-Sharma can you fix this?

**Comment by David-Sharma** [comment]
Update sent @Sing-Li

**Comment by Sing-Li** [comment]
> Update sent @Sing-Li

Please submit a PR, thanks.
