### ISSUE TITLE
[TO-DO]  Fully implement RecursiveCharacterTextSplitter (and other textsplitters)

### ISSUE THREAD

**Issue by Sing-Li** [llmshare/llmproto#8]
implement - model, view, controller, schema, code-fen  for  RecursiveCharacterTextSplitter

test on CodePage !

**Comment by Ashutosh0602** [comment]
Interested!

**Comment by Sing-Li** [comment]
Looking forward to your PR @Ashutosh0602 

Expanding this to include all the text  splitters

**Comment by spiritanand** [comment]
@Ashutosh0602 please refer https://js.langchain.com/docs/api/text_splitter/

**Comment by Ashutosh0602** [comment]
@Sing-Li Correct me if I am wrong. I gone through the code and docs and what I understood of RecursiveCharacterTextSplitter is dividing a text into smaller parts. And I have to create a block view that helps to change the chunk size, Chunk overlap, and other parameters. Then with the help of the controller I have to make changes in the generated code.

**Comment by Ashutosh0602** [comment]
@Sing-Li  Whenever you get time please go through previous comment.

**Comment by Sing-Li** [comment]
@Ashutosh0602 You just need to follow the pattern of the existing block, clone it, and then change everything to RecursiveCharacterTextSplitter's set of parameters.

As @spiritanand said in the meeting you organized - no need to attack the controller OR model at this point.  He is changing those part as we speak.

After that, you can look for other TextSplitters in the link I provided below and create blocks for them if you find any.

https://github.com/langchain-ai/langchainjs/tree/main/langchain/src

**Comment by Sing-Li** [comment]
@Ashutosh0602   we are closing this.     let me know in the channels when you can contribute again.
