### ISSUE TITLE
[TO-DO] fully implement  LoadSummarizationChain and OpenAI  (and other sum-chains + providers)

### ISSUE THREAD

**Issue by Sing-Li** [llmshare/llmproto#9]
implement - model, view, controller, schema, code-generation for LoadSummarizationChain and OpenAI

test on CodePage !

**Comment by praetorian2710** [comment]
Interested

**Comment by Sing-Li** [comment]
Thanks @praetorian2710      Looking forward to your PR.

**Comment by praetorian2710** [comment]
I was going through the complete codebase. OpenAI Seems to be done. Could You please elaborate on what changes i need to make? That will be extremely helpful. Also In LoadSummarizationChain , I need to create a parameter for returnIntermediateSteps: true... Right?

**Comment by spiritanand** [comment]
Refer to - https://github.com/langchain-ai/langchainjs/blob/main/examples/src/chains/summarization_map_reduce_intermediate_steps.ts

@praetorian2710 you will find all the imports and the parameters they would be needing.

**Comment by praetorian2710** [comment]
Yes @spiritanand , So the task is to create the import blocks, right?

**Comment by spiritanand** [comment]
@praetorian2710 create blocks/nodes that have a parameters of each import statement.

Later use these stored parameters in the generate code.

**Comment by praetorian2710** [comment]
ok got it

**Comment by Sing-Li** [comment]
@praetorian2710  please expand this to support all the LLM providers in Langchain.   Since @spiritanand will be handling most of the model bits with his refactor of the model/schema/db.

**Comment by Sing-Li** [comment]
And all the summarziation chains as well.

**Comment by praetorian2710** [comment]
> @praetorian2710 please expand this to support all the LLM providers in Langchain. Since @spiritanand will be handling most of the model bits with his refactor of the model/schema/db.

Could You elaborate a bit on this part? besides loadsummarizationchain and OpenAI, do i need to implement res block and also the import blocks?

**Comment by spiritanand** [comment]
https://js.langchain.com/docs/modules/model_io/models/llms/integrations/openai (and other LLMs)

<img width="365" alt="image" src="https://github.com/llmshare/llmproto/assets/53999998/4a5d885f-178a-44ac-93cb-a52f7444fc4f">

@Sing-Li we should get started with implementing a few of the more used models like:-
1. https://js.langchain.com/docs/modules/model_io/models/llms/integrations/huggingface_inference
2. https://js.langchain.com/docs/modules/model_io/models/llms/integrations/llama_cpp
3. https://js.langchain.com/docs/modules/model_io/models/llms/integrations/google_palm

This will help us see how our code is taking shape. 

Note for @praetorian2710 we will be using https://rxdb.info/quickstart.html as our DB. Please keep this in mind when implementing the LLMs.

Also, @praetorian2710 before you start with implementing other models, please have a look at the OpenAI model and make sure all the parameters are covered. Right now, we have only covered temperature.

<img width="845" alt="image" src="https://github.com/llmshare/llmproto/assets/53999998/7c0e8677-7dc9-4587-a4ce-46eeb07644f9">

**Comment by praetorian2710** [comment]
@spiritanand So first i need to add more parameters to Open AI block right?
And will the database schema and codes change?
If yes then im changing nothing in the database right now

**Comment by spiritanand** [comment]
Yes @praetorian2710 start by completing the OpenAI block.

Do not think of the db schema yet, that is being worked on ATM. Start working on the appropriate instance variables for OpenAI, its controllers and how you will send data to the server to update the db. For the actual db calls you can put in placeholders to tell what you would do once the DB is setup.

**Comment by Sing-Li** [comment]
@praetorian2710   after the OpenAI block, look into this directory:

https://github.com/langchain-ai/langchainjs/tree/main/langchain/src/llms

You want to add a new provider block for *every single one* that has an LLM provider inside.

ALSO look deep into this directory:

https://github.com/langchain-ai/langchainjs/tree/main/langchain/src/chains


You want to add a new block for every summarization chain contained.

There should be **no less than 10 new blocks** waiting to be created by you!   But the work should be relatively simple - without the database / model concerns that @spiritanand  is currently taking care of.

Hope that is understandable.

**Comment by Sing-Li** [comment]
We are closing this @praetorian2710         Let me know in the channel when you can contribute again.
